<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCecq7Rt\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCecq7Rt/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCecq7Rt.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCecq7Rt\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCecq7Rt\App_KernelDevDebugContainer([
    'container.build_hash' => 'Cecq7Rt',
    'container.build_id' => '252b6f74',
    'container.build_time' => 1674319113,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCecq7Rt');
